LRQA-62873 | master
mtambara/liferay-portal pull request #1024
Opened 2020-12-07 21:56 UTC by kyle-miho

https://issues.liferay.com/browse/LRQA-62873

2020-12-07 21:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-12-08 17:44 UTC, mtambara commented on modules/apps/static/portal-file-install/portal-file-install-test/src/testIntegration/java/com/liferay/portal/file/install/deploy/test/FileInstallConfigTest.java
> +			Assert.assertTrue(
What's the point of having two separate asserts here? You have the path, you can just assert a single message

2020-12-08 17:44 UTC, mtambara commented on modules/apps/static/portal-file-install/portal-file-install-test/src/testIntegration/java/com/liferay/portal/file/install/deploy/test/FileInstallConfigTest.java
> +
Use separate PIDs so that you can confirm that the cfg extension actually doesn't create a configuration

2020-12-08 20:43 UTC, kyle-miho commented
@mtambara fixed

2020-12-08 21:12 UTC, mtambara requested changes

2020-12-08 21:12 UTC, mtambara commented on modules/apps/static/portal-file-install/portal-file-install-test/src/testIntegration/java/com/liferay/portal/file/install/deploy/test/FileInstallConfigTest.java
> +				", please use .c onfig file instead.");
Typo?

2020-12-08 21:15 UTC, mtambara requested changes

2020-12-08 21:15 UTC, mtambara commented on modules/apps/static/portal-file-install/portal-file-install-test/src/testIntegration/java/com/liferay/portal/file/install/deploy/test/FileInstallConfigTest.java
> +			_configuration = _createConfiguration(configurationPid, content);
It doesn't look like you're doing anything with this. You need to give it a .cfg file with properties inside and assert that those properties aren't being read by the system

2020-12-15 22:30 UTC, kyle-miho commented
@mtambara finished changes

2020-12-21 16:26 UTC, mtambara requested changes

2020-12-21 16:26 UTC, mtambara commented on modules/apps/static/portal-file-install/portal-file-install-test/src/testIntegration/java/com/liferay/portal/file/install/deploy/test/FileInstallConfigTest.java
> +			Assert.assertNull(properties.get("testKeyDeprecated"));
You need to check `testKeyDeprecated` on the cfg configuration, not the config one. The purpose of the check is to make sure that the cfg configuration actually didn't get loaded

2021-01-04 19:27 UTC, kyle-miho commented
@mtambara updated the key i was reading the config from. I think i did it correctly?

2021-01-07 17:58 UTC, mtambara commented
See https://github.com/shuyangzhou/liferay-portal/pull/9707

2021-01-07 17:58 UTC, closed without merging